/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AiConfig {
  default: string
}

export interface CanvasConfig {
  fill_drawing: boolean
  double_click?: string
  num_backups: number
  crosshair: Crosshair
}

export interface Config {
  auto_save: boolean
  display_label_popup: boolean
  with_image_data: boolean
  keep_prev: boolean
  keep_prev_scale: boolean
  keep_prev_brightness_contrast: boolean
  logger_level: string
  flags?: string
  label_flags?: string
  labels?: Array<string>
  file_search?: string
  sort_labels: boolean
  validate_label?: string
  default_shape_color: Array<number>
  shape_color?: string
  shift_auto_shape_color: number
  label_colors?: string
  shape: ShapeConfig
  ai: AiConfig
  flag_dock: DockConfig
  label_dock: DockConfig
  shape_dock: DockConfig
  file_dock: DockConfig
  show_label_text_field: boolean
  label_completion: string
  fit_to_content: FitToContent
  epsilon: number
  canvas: CanvasConfig
  shortcuts: Shortcuts
}

export interface Crosshair {
  polygon: boolean
  rectangle: boolean
  circle: boolean
  line: boolean
  point: boolean
  linestrip: boolean
  ai_polygon: boolean
  ai_mask: boolean
}

export interface DockConfig {
  show: boolean
  closable: boolean
  movable: boolean
  floatable: boolean
}

export interface FitToContent {
  column: boolean
  row: boolean
}

export interface ShapeConfig {
  line_color: Array<number>
  fill_color: Array<number>
  vertex_fill_color: Array<number>
  select_line_color: Array<number>
  select_fill_color: Array<number>
  hvertex_fill_color: Array<number>
  point_size: number
}

export type Shortcut = string | Array<string> | null

export interface Shortcuts {
  close?: Shortcut
  open?: Shortcut
  open_dir?: Shortcut
  quit?: Shortcut
  save?: Shortcut
  save_as?: Shortcut
  save_to?: Shortcut
  delete_file?: Shortcut
  delete_image_file?: Shortcut
  open_next?: Shortcut
  open_prev?: Shortcut
  zoom_in?: Shortcut
  zoom_out?: Shortcut
  zoom_to_original?: Shortcut
  fit_window?: Shortcut
  fit_width?: Shortcut
  create_polygon?: Shortcut
  create_rectangle?: Shortcut
  create_circle?: Shortcut
  create_line?: Shortcut
  create_point?: Shortcut
  create_linestrip?: Shortcut
  edit_shape?: Shortcut
  delete_shape?: Shortcut
  duplicate_shape?: Shortcut
  copy_shape?: Shortcut
  paste_shape?: Shortcut
  undo?: Shortcut
  undo_last_point?: Shortcut
  edit_label?: Shortcut
  toggle_keep_prev_mode?: Shortcut
  remove_selected_point?: Shortcut
  show_all_shapes?: Shortcut
  hide_all_shapes?: Shortcut
  toggle_all_shapes?: Shortcut
}
export declare function getConfig(): Config

export declare function setConfig(config: Config): void
